[package]
name = "haha"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.10.1"
winit = "0.25.0"
env_logger = "0.9"